version: '3'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"

  node:
    restart: always
    build: .
    ports:
      - "5000:5000"

  pyserver:
    build: ./server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
